---
title: "Optimizing clinical dosing of combination broadly neutralizing antibodies for HIV prevention."
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This website is a research compendium for the following paper:

Optimizing clinical dosing of combination broadly neutralizing antibodies for HIV prevention.
Bryan T. Mayer, Allan C. deCamp, Yunda Huang, Joshua T. Schiffer, Raphael Gottardo, Peter B. Gilbert, Daniel B. Reeves.
Plos Comp Bio. *Accepted.* 2022. 


### Shiny Application

- [http://bnabpkpd.fredhutch.org/](http://bnabpkpd.fredhutch.org/)
- Code for the shiny app is hosted here: https://github.com/FredHutch/bnAb_PKPD_Simulation_Shiny

### Primary Analyses

- [Code and functions used throughout analysis](opt-sims-background.html)
- Theoretical sensitivity optimization analysis.
  - [Script used to conduct simulations.](https://github.com/bryanmayer/pkpd-bnab-project/blob/main/code/simulation-batch.R)
  - [Accessing raw simulation results.](process-sims.html)
  - [Python code to perform sensitivity analysis.](sensitivity-analysis.html)
- [Bi-specific bnAb scenario.](bispecific.html)
- [Three bnAb combination optimization.](empirical-case-study.html)


### Supplementary Analyses

- [Exploration of combined titer measurements.](titer-analysis.html)
- [Estimation of Hill slope from CATNAP data.](hill-slope-meta.html)

### External data sources

- [Pulling CATNAP data.](process_catnap.html)
- [PK data for combination optimization.](https://github.com/bryanmayer/pkpd-bnab-project/tree/main/data/empirical-pk-data/)
- [AMP IC80 vs. PE data.](https://www.nejm.org/na101/home/literatum/publisher/mms/journals/content/nejm/2021/nejm_2021.384.issue-11/nejmoa2031738/20210611/images/img_small/nejmoa2031738_f3.jpeg) - [data here](https://github.com/bryanmayer/pkpd-bnab-project/blob/main/data/nejm_fig3a.xlsx)

