---
title: " Combination titer analysis"
author: "Bryan"
date: "`r Sys.Date()`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r, message = F, warning = F}
library(metR)
library(tidyverse)
library(kableExtra)
library(cowplot)
source("code/neutralization-funs.R")
source("code/onecmptPKPD-sims.R")
theme_set(theme_bw())
```


```{r conc-setup}

odds2fraction = function(odds_1, odds_2, return_all_frac = F){
  frac_1 = odds_1/(odds_1+odds_2)
  if(return_all_frac) return(c(frac_1, 1 - frac_1))
  frac_1
}


paste_ic50s = function(x) paste0("{",paste(x, collapse = ", "), "}")
conc_range = 10^(seq(-2, 2.5,  length = 50))
conc_grid = crossing(a = conc_range, b = conc_range)
```

# Two mAb vs. single virus

Same IC50 -- highlights the issues with titer and BH.

```{r twomab-onevirus}
IC501 = 1
IC502 = 1

single_virus_example = crossing(a = conc_range, b = conc_range) %>%
  rowwise() %>%
  mutate(
    ID501 = a/IC501,
    ID502 = b/IC502,
    minNeut_ID50 = min(ID501, ID502),
    minNeut_iip = log10(1+minNeut_ID50),
    maxNeut_ID50 = max(ID501, ID502),
    maxNeut_iip = log10(1+ maxNeut_ID50),
    additivity_ID50 = ID501 + ID502,
    additivity_iip = log10(1+additivity_ID50),
    BH_ID50 = calc_BHID50(ID501, ID502),
    BH_iip = -log10(1 - titer2BH(ID501, ID502))
  ) %>%
  gather(endpoint, value, -a, -b, -ID501, -ID502) %>%
  separate(endpoint, into = c("interaction", "endpoint")) %>%
  spread(endpoint, value)

single_virus_example %>%
  mutate(
    interaction = interaction_labeller(interaction)
  ) %>%
  ggplot(aes(x = ID501, y = ID502, fill = iip)) +
  geom_tile() +
  scale_x_log10(expand = c(0,0), breaks = 10^(0:3), labels = c("1", "10", "100", "1000")) +
  scale_y_log10(expand = c(0,0), breaks = 10^(0:3), labels = c("1", "10", "100", "1000")) +
  geom_contour(aes(z = (10^iip - 1)), breaks = c(1, 10, 100, 1000)) +
  geom_contour(aes(z = (ID50)), breaks = c(1, 10, 100, 1000), colour = "black") +
  geom_text_contour(aes(z = log10(ID50 + 1)), breaks = (1:3), size = 5) +
  facet_wrap(~interaction) +
  labs(x = expression(paste("ID50"[1])), y = expression(paste("ID50"[2])),
       fill = "Neutralization IIP") +
  scale_fill_viridis_c() +
  theme(legend.position = "top")

# titer_iip_pl = tibble(
#   ID50 = 10^seq(-1, 4, length = 10),
#   iip = log10(1+ ID50),
#   interaction = "single mAb"
# )
# 
single_virus_example %>%
  subset(interaction == "BH") %>%
  ggplot(aes(x = ID50, y = iip)) +
  geom_line() +
  geom_step() +
  scale_x_log10() +
  labs(y = "BH IIP")

```

Focusing on additivity and BH to highlight non-uniqueness in BH. Here, we take use slightly different IC50s and plot combined ID50 vs. neutralization.

```{r single-virus-ic50s}

conc_range = 10^(seq(-2, 2.5,  length = 50))
IC50_list = list(c(1e-2, 1e-2),
                 c(1e-2, 1e-1),
                 c(0.1, 0.1),
                 c(1, .1))

single_virus_example2 = purrr::map_df(c(0.1, 1, 10), function(x) {
  map_df(IC50_list, function(y){
  tibble(input_conc = conc_range,
         ratioAB = x,
         IC50lab = paste_ic50s(y)
         ) %>%
    rowwise() %>%
    mutate(
      ID501 = input_conc/(1 + x) / y[1],
      ID502 = input_conc/(1 + 1/x) / y[2],
      additivity_ID50 = ID501 + ID502,
      additivity_neut = 1 - 1/(1+ additivity_ID50),
      BH_ID50 = calc_BHID50(ID501, ID502),
      BH_neut = titer2BH(ID501, ID502)
    ) %>%
    gather(endpoint, value,-input_conc, -ratioAB, -ID501,-ID502, -IC50lab) %>%
    separate(endpoint, into = c("interaction", "endpoint")) %>%
    spread(endpoint, value)
})
})
titer_iip_pl = tibble(
   ID50 = unique(single_virus_example2$ID50),
   neut = titer2neut(ID50)
 )
 
```


```{r single-virus-pl, fig.height=8}

single_virus_example2 %>%
    mutate(
      interaction = paste(interaction_labeller(interaction), "ID50"),
      ratio_lab = factor(ratioAB, levels = c(0.1, 0.5, 1, 2, 10),
                         labels = c("10:1", "2:1", "1:1", "1:2", "1:10"))
    ) %>%
  ggplot(aes(
    x = ID50,
    y = -log10(1 - neut),
    colour = ratio_lab
  )) +
  geom_line() +
  geom_line(data = titer_iip_pl, colour = "black", linetype = "dashed") +
  scale_x_log10(limits = c(0.5, 2500)) +
  scale_y_continuous(limits = c(NA, 6.2)) +
  facet_grid(cols = vars(interaction), rows = vars(IC50lab),
             switch = "x") +
  labs(x = "", colour = "conc. ratio", y = "IIP") +
  theme(legend.position = "top", strip.placement = "outside", 
        strip.background.x = element_blank())


```


# Multiple viruses

## Simulated data

```{r sample-viruses}
vseed = 132432

pd_data = tibble(muIC50_1 = -3, sigIC50_1 = 0.5, omega_1 = 0.65,
                 muIC50_2 = -2, sigIC50_2 = 0.5, omega_2 = 0.8)
viral_panel = .sample_IC50s(500 - length(IC50_list), pd_data, virus_seed = vseed) %>%
  mutate(mark = F) %>%
  bind_rows( map_df(IC50_list, ~(tibble(IC50_1 = .x[1], IC50_2 = .x[2], mark = T))))

(
  viral_panel %>%
    mutate_if(is.numeric, ~ (if_else(.x > 10, 10, .x))) %>%
    ggplot(aes(
      x = IC50_1,
      y = IC50_2,
      colour = factor(mark)
    )) +
    geom_point(aes(alpha = factor(mark))) +
    scale_x_log10("IC50A") +
    scale_y_log10("IC50B") +
    scale_color_manual(guide = F, values = c("black", "red")) +
    scale_alpha_manual(guide = F, values = c(0.5, 1)) +
    geom_abline()
)  %>%
  ggExtra::ggMarginal(type = "histogram")

```

## Real data

incomplete

```{r use-real-data, eval = F}

ic50_cutoff = 10

catnap_dat_raw = read_rds("output/processed_catnap_assay.rds") 
catnap_dat = catnap_dat_raw %>%
  subset(Antibody  %in% c("10-1074", "3BNC117","PGDM1400", "PGT121")) %>%
  group_by(Virus, Reference) %>%
  mutate(
    total_ab = n(),
    clean_IC50 = if_else(clean_IC50 >= ic50_cutoff, Inf, clean_IC50),
    clean_IC50_plot = if_else(clean_IC50 >= ic50_cutoff, ic50_cutoff * 10, clean_IC50)
  ) %>%
  filter(total_ab == 4) %>%
  select(Virus, Antibody, clean_IC50, clean_IC50_plot, subtype, Reference) %>%
  ungroup()

# wide for pkpd analysis
pd_data_set1 = catnap_dat %>%
  subset(Antibody %in% c("10-1074", "3BNC117")) %>%
  dplyr::select(-clean_IC50_plot) %>%
  pivot_wider(names_from = "Antibody", values_from = "clean_IC50")

pd_data_set2 = catnap_dat %>%
  subset(Antibody %in% c("PGDM1400", "PGT121")) %>%
  dplyr::select(-clean_IC50_plot) %>%
  pivot_wider(names_from = "Antibody", values_from = "clean_IC50")


```

```{r, eval = F}

drA = map2_df(conc_grid$a, conc_grid$b, function(i, j){
  pd_data_set1 %>%
    mutate(
      BH = titer2BH(i/`10-1074`, j/`3BNC117`),
      BH_ID50 = calc_BHID50(i/`10-1074`, j/`3BNC117`)) %>%
    summarize(
      mean_iip = mean(-log10(1 - BH)),
      mean_ID50 = mean(BH_ID50),
      mean_log10ID50 = mean(log10(BH_ID50))
      ) %>%
    mutate(mab_3bnc = j, mab_1074 = i)
}) %>%
  mutate(IIP_thresh = mean_iip < 2)

drB = map2_df(conc_grid$a, conc_grid$b, function(i, j){
  pd_data_set2 %>%
    mutate(
      BH = titer2BH(i/`PGT121`, j/`PGDM1400`),
      BH_ID50 = calc_BHID50(i/`PGT121`, j/`PGDM1400`)) %>%
    summarize(
      mean_iip = mean(-log10(1 - BH)),
      mean_ID50 = mean(BH_ID50),
      mean_log10ID50 = mean(log10(BH_ID50))
      ) %>%
    mutate(mab_pgt = i, mab_pgdm = j)
})

color_range = c(min(drA$mean_iip, drB$mean_iip), max(drA$mean_iip, drB$mean_iip))

```


```{r, eval = F}

pA = drA %>%
  ggplot(aes(x = mab_3bnc, y = mab_1074, fill = mean_iip)) +
  scale_x_log10(expand = c(0, 0)) +
  scale_y_log10(expand = c(0, 0)) +
  geom_tile() +
  geom_contour(aes(z = mean_log10ID50), breaks = 1:3) +
  metR::geom_label_contour(aes(z = mean_log10ID50), breaks = 1:3) +
  geom_contour(aes(z = mean_iip), breaks = 2, colour = "black") +
  scale_fill_viridis_c(limits = color_range) + 
  geom_abline(linetype = "dashed") 
pA

pB = drB %>%
  ggplot(aes(x = mab_pgt, y = mab_pgdm, fill = mean_iip)) +
  scale_x_log10(expand = c(0, 0)) +
  scale_y_log10(expand = c(0, 0)) +
  geom_tile() +
  geom_contour(aes(z = log10(mean_geoID50)), breaks = 1:3) +
  metR::geom_label_contour(aes(z = mean_geoID50), breaks = 10^(1:3)) +
  geom_contour(aes(z = mean_iip), breaks = 2, colour = "black") +
  scale_fill_viridis_c(limits = color_range) + 
  geom_abline(linetype = "dashed") 

leg = get_legend(pB + theme(legend.position = "top"))

plot_grid(leg,
  plot_grid(pA + theme(legend.position = "none"), pB + theme(legend.position = "none")),
  nrow = 2, rel_heights = c(2, 12)
)

```
